---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-user
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-user
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-user
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default